import json
import re

with open('en_ui.json', 'r') as f:
    en_ui = json.load(f)

de_translations = {
  "init_bandwidth_monitor": "Bandbreiten-Monitor initialisieren...",
  "proxy_speed": "Proxy-Geschwindigkeit",
  "mbps": "Mbit/s",
  "active_streams": "Aktive Streams",
  "data_proxied": "Geproxte Daten",
  "ip_lookup_unavailable": "IP-Suche nicht verfügbar",
  "egress_ip": "Ausgangs-IP",
  "real_time_system_performance_a": "Echtzeit-Systemleistung und -aktivität",
  "bandwidth_usage": "Bandbreitennutzung",
  "real_time_throughput__last_2_m": "Echtzeit-Durchsatz (letzte 2 Minuten)",
  "now_playing": "Läuft gerade",
  "playlists_with_direct_streams": "Playlists mit Direct Streams umgehen den Proxy und werden hier nicht angezeigt",
  "direct_stream": "Direkter Stream",
  "not_shown": "nicht angezeigt",
  "via": "über",
  "vpn_proxied": "VPN-geproxt",
  "quiet_on_the_wire": "Ruhig in der Leitung...",
  "no_active_streams": "Keine aktiven Streams",
  "manage_and_configure_your_iptv": "Verwalte und konfiguriere deine IPTV-Playlists",
  "new_playlist": "Neue Playlist",
  "playlist_name": "Playlist-Name",
  "api_username": "API-Benutzername",
  "api_password": "API-Passwort",
  "direct_streams": "Direkte Streams",
  "return_the_original_source_str": "Ursprüngliche Quell-Stream-URLs zurückgeben, anstatt über diesen Server zu proxen. Umgeht den Proxy vollständig.",
  "create": "Erstellen",
  "duplicate_playlist": "Playlist duplizieren",
  "copies_all_categories_and_mapp": "Kopiert alle Kategorien und Zuordnungen. Geben Sie unten neue Anmeldeinformationen ein.",
  "new_playlist_details": "Neue Playlist-Details",
  "proxy_api_credentials": "Proxy-API-Anmeldeinformationen",
  "upstream_provider_credentials": "Upstream-Anbieter-Anmeldeinformationen",
  "duplicate": "Duplizieren",
  "cancel": "Abbrechen",
  "add_playlist": "Playlist hinzufügen",
  "import_m3u": "M3U importieren",
  "import_xtream_codes_api": "Xtream Codes API importieren",
  "import_m3u_playlist": "M3U-Playlist importieren",
  "m3u_url": "M3U URL",
  "no_playlists": "Keine Playlists",
  "get_started_by_adding_your_fir": "Beginne, indem du deine erste Playlist hinzufügst.",
  "manage_and_configure_your_iptv_1": "Verwalte und konfiguriere deine IPTV-Playlists.",
  "delete_playlist": "Playlist löschen",
  "are_you_sure_you_want_to_delet": "Möchten Sie diese Playlist wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden.",
  "delete": "Löschen",
  "playlist_url": "Playlist-URL",
  "xtream_api_details": "Xtream-API-Details",
  "quality_label_format": "Qualitätslabel-Format",
  "the_format_for_quality_tags_af": "Das Format für Qualitäts-Tags, die nach Stream-Namen angehängt werden.",
  "example_result": "Beispielergebnis",
  "variables": "Variablen",
  "save": "Speichern",
  "something_went_wrong": "Etwas ist schief gelaufen",
  "reload_application": "Anwendung neu laden",
  "overview": "Übersicht",
  "sources": "Quellen",
  "categories": "Kategorien",
  "streams": "Streams",
  "users": "Benutzer",
  "epg": "EPG",
  "no_sources_configured": "Keine Quellen konfiguriert",
  "add_a_source_to_get_started": "Fügen Sie eine Quelle hinzu, um zu beginnen",
  "loading_sources": "Quellen laden...",
  "manage_upstream_iptv_sources": "Verwalten Sie vorgelagerte IPTV-Quellen",
  "m3u": "M3U",
  "xtream": "Xtream",
  "xtream_api": "Xtream API",
  "m3u_file": "M3U-Datei",
  "m3u_file_is_too_large___100mb_": "M3U-Datei ist zu groß (>100MB)",
  "only__m3u_and__txt_files_are_s": "Nur .m3u und .txt Dateien werden unterstützt",
  "uploading_file": "Datei hochladen...",
  "select_local_file": "Lokale Datei auswählen",
  "or_drag_and_drop": "Oder Drag & Drop",
  "url": "URL",
  "username": "Benutzername",
  "password": "Password",
  "use_upstream_epg": "Upstream-EPG verwenden",
  "auto_sync": "Automatische Synchronisierung",
  "add_source": "Quelle hinzufügen",
  "save_changes": "Änderungen speichern",
  "delete_source": "Quelle löschen",
  "are_you_sure_you_want_to_delet_1": "Möchten Sie diese Quelle wirklich löschen?",
  "sync_now": "Jetzt synchronisieren",
  "syncing": "Synchronisieren...",
  "manage_your_xmltv_guides": "Verwalten Sie Ihre XMLTV-Guides",
  "add_epg_provider": "EPG-Anbieter hinzufügen",
  "include_this_source_s_epg_guid": "Schließen Sie den EPG-Guide dieser Quelle ein (",
  "save_epg": "EPG speichern",
  "add_epg": "EPG hinzufügen",
  "delete_epg_provider": "EPG-Anbieter löschen",
  "are_you_sure_you_want_to_delet_2": "Möchten Sie diesen EPG-Anbieter wirklich löschen?",
  "last_updated": "Zuletzt aktualisiert",
  "never": "Nie",
  "channels": "Kanäle",
  "loading": "Laden...",
  "settings": "Einstellungen",
  "system_configuration": "Systemkonfiguration",
  "quality_labels": "Qualitätslabels",
  "define_how_quality_tags_should": "Legen Sie fest, wie Qualitäts-Tags standardmäßig formatiert werden sollen. Dies kann pro Playlist überschrieben werden.",
  "saving": "Speichern...",
  "user_management": "Benutzerverwaltung",
  "manage_system_accounts_and_the": "Verwalten Sie Systemkonten und deren Berechtigungen",
  "add_user": "Benutzer hinzufügen",
  "role": "Rolle",
  "administrator": "Administrator",
  "viewer": "Zuschauer",
  "save_user": "Benutzer speichern",
  "delete_user": "Benutzer löschen",
  "are_you_sure_you_want_to_delet_3": "Möchten Sie diesen Benutzer wirklich löschen?",
  "current_user": "Aktueller Benutzer",
  "quality_label": "Qualitätslabel",
  "disable_all": "Alle deaktivieren",
  "regex_rename": "Regex-Umbenennung",
  "apply_regex_rename": "Regex-Umbenennung anwenden",
  "quality_scan": "Qualitätsscan",
  "concurrency": "Nebenläufigkeit",
  "skip_already_scanned": "Bereits gescannte überspringen",
  "scan": "Scannen",
  "visibility": "Sichtbarkeit",
  "show_all": "Alle anzeigen",
  "hide_all": "Alle ausblenden",
  "order": "Reihenfolge",
  "move_to_top": "Nach oben verschieben",
  "category_name": "Kategoriename",
  "category_icon_url": "Kategorie-Icon-URL",
  "no_streams_in_selected_categor": "Keine Streams in der ausgewählten Kategorie gefunden",
  "search": "Suche",
  "global_search_across_all_strea": "Globale Suche über alle Streams",
  "no_results_found": "Keine Ergebnisse gefunden",
  "hidden": "Versteckt",
  "no_epg": "Kein EPG",
  "add": "Hinzufügen",
  "remove": "Entfernen",
  "advanced_analytics": "Erweiterte Analysen",
  "api_endpoint": "API-Endpunkt",
  "audio": "Audio",
  "auto_match": "Automatische Zuordnung",
  "auto_match_by_name": "Automatische Zuordnung nach Name",
  "auto_match_epg": "Automatische EPG-Zuordnung",
  "auto_match_epg_channels_by_nam": "EPG-Kanäle automatisch nach Namen zuordnen",
  "cached": "Zwischengespeichert",
  "catchup": "Catchup",
  "clear": "Löschen",
  "codec": "Codec",
  "completed": "Abgeschlossen",
  "configure_which_streams_are_in": "Konfigurieren Sie, welche Streams in dieser Playlist enthalten sind",
  "create_playlist": "Playlist erstellen",
  "custom_categories": "Benutzerdefinierte Kategorien",
  "custom_icon": "Benutzerdefiniertes Icon",
  "custom_name": "Benutzerdefinierter Name",
  "edit": "Bearbeiten",
  "edit_category": "Kategorie bearbeiten",
  "edit_playlist": "Playlist bearbeiten",
  "edit_source": "Quelle bearbeiten",
  "edit_stream": "Stream bearbeiten",
  "editor": "Editor",
  "enable": "Aktivieren",
  "enable_all": "Alle aktivieren",
  "epg_id": "EPG ID",
  "epg_source": "EPG-Quelle",
  "export": "Exportieren",
  "failed": "Fehlgeschlagen",
  "general": "Allgemein",
  "global_search": "Globale Suche",
  "hide": "Ausblenden",
  "import": "Importieren",
  "live": "Live",
  "live_tv": "Live TV",
  "mac": "MAC",
  "movies": "Filme",
  "name": "Name",
  "new_category": "Neue Kategorie",
  "next": "Weiter",
  "none": "Keine",
  "not_configured": "Nicht konfiguriert",
  "offline": "Offline",
  "online": "Online",
  "password_optional": "Passwort (Optional)",
  "pattern": "Muster",
  "play": "Abspielen",
  "playlist": "Playlist",
  "port": "Port",
  "proxy": "Proxy",
  "quality": "Qualität",
  "refresh": "Aktualisieren",
  "replacement": "Ersatz",
  "s_idx": "S-Idx",
  "save_and_close": "Speichern & Schließen",
  "scan_all": "Alle scannen",
  "search_channels": "Kanäle suchen...",
  "search_streams": "Streams suchen...",
  "select_a_category": "Kategorie auswählen",
  "select_a_playlist": "Playlist auswählen",
  "select_a_source": "Quelle auswählen",
  "series": "Serien",
  "server": "Server",
  "server_url": "Server URL",
  "show": "Anzeigen",
  "source": "Quelle",
  "status": "Status",
  "stream": "Stream",
  "stream_details": "Stream-Details",
  "stream_id": "Stream ID",
  "stream_url": "Stream URL",
  "sync": "Sync",
  "sync_all": "Alle synchronisieren",
  "synced": "Synchronisiert",
  "time": "Zeit",
  "title": "Titel",
  "total": "Gesamt",
  "type": "Typ",
  "unhide": "Einblenden",
  "unknown": "Unbekannt",
  "update": "Aktualisieren",
  "update_playlist": "Playlist aktualisieren",
  "upstream": "Upstream",
  "video": "Video",
  "vod": "VOD"
}

es_translations = {
  "init_bandwidth_monitor": "Iniciar monitor de ancho de banda...",
  "proxy_speed": "Velocidad del proxy",
  "mbps": "Mbps",
  "active_streams": "Streams activos",
  "data_proxied": "Datos en proxy",
  "ip_lookup_unavailable": "Búsqueda de IP no disponible",
  "egress_ip": "IP de salida",
  "real_time_system_performance_a": "Rendimiento y actividad del sistema en tiempo real",
  "bandwidth_usage": "Uso de ancho de banda",
  "real_time_throughput__last_2_m": "Rendimiento en tiempo real (últimos 2 minutos)",
  "now_playing": "Reproduciendo ahora",
  "playlists_with_direct_streams": "Las listas de reproducción con Direct Streams omiten el proxy y no aparecerán aquí",
  "direct_stream": "Stream directo",
  "not_shown": "No se muestra",
  "via": "vía",
  "vpn_proxied": "Proxy VPN",
  "quiet_on_the_wire": "Silencio en la línea...",
  "no_active_streams": "No hay streams activos",
  "manage_and_configure_your_iptv": "Administre y configure sus listas de reproducción IPTV",
  "new_playlist": "Nueva lista de reproducción",
  "playlist_name": "Nombre de la lista de reproducción",
  "api_username": "Nombre de usuario de API",
  "api_password": "Contraseña de API",
  "direct_streams": "Streams directos",
  "return_the_original_source_str": "Devolver las URL de los streams de origen en lugar de usar proxy. Omite completamente el proxy.",
  "create": "Crear",
  "duplicate_playlist": "Duplicar lista de reproducción",
  "copies_all_categories_and_mapp": "Copia todas las categorías y asignaciones. Introduzca nuevas credenciales a continuación.",
  "new_playlist_details": "Detalles de la nueva lista",
  "proxy_api_credentials": "Credenciales de API Proxy",
  "upstream_provider_credentials": "Credenciales de proveedor Upstream",
  "duplicate": "Duplicar",
  "cancel": "Cancelar",
  "add_playlist": "Añadir lista",
  "import_m3u": "Importar M3U",
  "import_xtream_codes_api": "Importar API Xtream Codes",
  "import_m3u_playlist": "Importar lista M3U",
  "m3u_url": "URL M3U",
  "no_playlists": "Sin listas",
  "get_started_by_adding_your_fir": "Comience añadiendo su primera lista de reproducción.",
  "manage_and_configure_your_iptv_1": "Administre y configure sus listas de reproducción IPTV.",
  "delete_playlist": "Eliminar lista",
  "are_you_sure_you_want_to_delet": "¿Estás seguro de que deseas eliminar esta lista de reproducción? Esta acción no se puede deshacer.",
  "delete": "Eliminar",
  "playlist_url": "URL de la lista",
  "xtream_api_details": "Detalles API Xtream",
  "quality_label_format": "Formato de etiqueta de calidad",
  "the_format_for_quality_tags_af": "El formato para las etiquetas de calidad adjuntas después de los nombres de los streams.",
  "example_result": "Resultado de ejemplo",
  "variables": "Variables",
  "save": "Guardar",
  "something_went_wrong": "Algo salió mal",
  "reload_application": "Recargar aplicación",
  "overview": "Visión general",
  "sources": "Fuentes",
  "categories": "Categorías",
  "streams": "Streams",
  "users": "Usuarios",
  "epg": "EPG",
  "no_sources_configured": "No hay fuentes configuradas",
  "add_a_source_to_get_started": "Agregue una fuente para comenzar",
  "loading_sources": "Cargando fuentes...",
  "manage_upstream_iptv_sources": "Administrar fuentes IPTV upstream",
  "m3u": "M3U",
  "xtream": "Xtream",
  "xtream_api": "Xtream API",
  "m3u_file": "Archivo M3U",
  "m3u_file_is_too_large___100mb_": "Archivo M3U demasiado grande (>100MB)",
  "only__m3u_and__txt_files_are_s": "Solo se admiten archivos .m3u y .txt",
  "uploading_file": "Subiendo archivo...",
  "select_local_file": "Seleccionar archivo local",
  "or_drag_and_drop": "O arrastrar y soltar",
  "url": "URL",
  "username": "Usuario",
  "password": "Password",
  "use_upstream_epg": "Usar EPG upstream",
  "auto_sync": "Sincronización automática",
  "add_source": "Agregar fuente",
  "save_changes": "Guardar cambios",
  "delete_source": "Eliminar fuente",
  "are_you_sure_you_want_to_delet_1": "¿Está seguro de que desea eliminar esta fuente?",
  "sync_now": "Sincronizar ahora",
  "syncing": "Sincronizando...",
  "manage_your_xmltv_guides": "Administra tus guías XMLTV",
  "add_epg_provider": "Agregar proveedor EPG",
  "include_this_source_s_epg_guid": "Incluir la guía EPG de esta fuente (",
  "save_epg": "Guardar EPG",
  "add_epg": "Añadir EPG",
  "delete_epg_provider": "Eliminar proveedor EPG",
  "are_you_sure_you_want_to_delet_2": "¿Está seguro de que desea eliminar este proveedor de EPG?",
  "last_updated": "Última actualización",
  "never": "Nunca",
  "channels": "Canales",
  "loading": "Cargando...",
  "settings": "Ajustes",
  "system_configuration": "Configuración del sistema",
  "quality_labels": "Etiquetas de calidad",
  "define_how_quality_tags_should": "Defina cómo deben formatearse las etiquetas de calidad por defecto. Se puede sobrescribir por lista.",
  "saving": "Guardando...",
  "user_management": "Gestión de usuarios",
  "manage_system_accounts_and_the": "Administre cuentas del sistema y sus permisos",
  "add_user": "Añadir usuario",
  "role": "Rol",
  "administrator": "Administrador",
  "viewer": "Espectador",
  "save_user": "Guardar usuario",
  "delete_user": "Eliminar usuario",
  "are_you_sure_you_want_to_delet_3": "¿Está seguro de que desea eliminar este usuario?",
  "current_user": "Usuario actual",
  "quality_label": "Etiqueta de calidad",
  "disable_all": "Deshabilitar todo",
  "regex_rename": "Renombrar con Regex",
  "apply_regex_rename": "Aplicar renombramiento Regex",
  "quality_scan": "Escaneo de calidad",
  "concurrency": "Concurrencia",
  "skip_already_scanned": "Omitir ya escaneados",
  "scan": "Escanear",
  "visibility": "Visibilidad",
  "show_all": "Mostrar todo",
  "hide_all": "Ocultar todo",
  "order": "Orden",
  "move_to_top": "Mover a la parte superior",
  "category_name": "Nombre de categoría",
  "category_icon_url": "URL del icono de categoría",
  "no_streams_in_selected_categor": "No se encontraron streams en la categoría",
  "search": "Buscar",
  "global_search_across_all_strea": "Búsqueda global en todos los streams",
  "no_results_found": "No se encontraron resultados",
  "hidden": "Oculto",
  "no_epg": "Sin EPG",
  "add": "Añadir",
  "remove": "Quitar",
  "advanced_analytics": "Análisis avanzado",
  "api_endpoint": "Endpoint API",
  "audio": "Audio",
  "auto_match": "Coincidencia automática",
  "auto_match_by_name": "Coincidir por nombre",
  "auto_match_epg": "Coincidir EPG auto",
  "auto_match_epg_channels_by_nam": "Coincidir canales EPG por nombre",
  "cached": "En caché",
  "catchup": "Catchup",
  "clear": "Limpiar",
  "codec": "Códec",
  "completed": "Completado",
  "configure_which_streams_are_in": "Configura qué streams están en esta lista",
  "create_playlist": "Crear lista de reproducción",
  "custom_categories": "Categorías personalizadas",
  "custom_icon": "Icono personalizado",
  "custom_name": "Nombre personalizado",
  "edit": "Editar",
  "edit_category": "Editar categoría",
  "edit_playlist": "Editar lista",
  "edit_source": "Editar fuente",
  "edit_stream": "Editar stream",
  "editor": "Editor",
  "enable": "Habilitar",
  "enable_all": "Habilitar todo",
  "epg_id": "ID de EPG",
  "epg_source": "Fuente EPG",
  "export": "Exportar",
  "failed": "Fallido",
  "general": "General",
  "global_search": "Búsqueda global",
  "hide": "Ocultar",
  "import": "Importar",
  "live": "En vivo",
  "live_tv": "TV en vivo",
  "mac": "MAC",
  "movies": "Películas",
  "name": "Nombre",
  "new_category": "Nueva categoría",
  "next": "Siguiente",
  "none": "Ninguno",
  "not_configured": "No configurado",
  "offline": "Desconectado",
  "online": "En línea",
  "password_optional": "Contraseña (Opcional)",
  "pattern": "Patrón",
  "play": "Reproducir",
  "playlist": "Lista de reproducción",
  "port": "Puerto",
  "proxy": "Proxy",
  "quality": "Calidad",
  "refresh": "Actualizar",
  "replacement": "Reemplazo",
  "s_idx": "S-Idx",
  "save_and_close": "Guardar y cerrar",
  "scan_all": "Escanear todo",
  "search_channels": "Buscar canales...",
  "search_streams": "Buscar streams...",
  "select_a_category": "Selecciona categoría",
  "select_a_playlist": "Selecciona lista",
  "select_a_source": "Selecciona fuente",
  "series": "Series",
  "server": "Servidor",
  "server_url": "URL del servidor",
  "show": "Mostrar",
  "source": "Fuente",
  "status": "Estado",
  "stream": "Stream",
  "stream_details": "Detalles del stream",
  "stream_id": "ID del Stream",
  "stream_url": "URL del Stream",
  "sync": "Sync",
  "sync_all": "Sincronizar todo",
  "synced": "Sincronizado",
  "time": "Tiempo",
  "title": "Título",
  "total": "Total",
  "type": "Tipo",
  "unhide": "Mostrar",
  "unknown": "Desconocido",
  "update": "Actualizar",
  "update_playlist": "Actualizar lista",
  "upstream": "Upstream",
  "video": "Vídeo",
  "vod": "VOD"
}

# The previous python script missed doing this dynamically or applying regex accurately because I overwrote it or missed cases. Let's do it right.
with open('src/locales/de/translation.json', 'r') as f:
    de_data = json.load(f)

for k, v in en_ui.items():
    if k in de_translations:
        de_data['translation']['ui'][k] = de_translations[k]
    else:
        # Check if it has a [DE] prefix, if so, strip it, so the English strings render without [DE] tags at least!
        val = de_data['translation']['ui'].get(k, '')
        if isinstance(val, str) and val.startswith('[DE] '):
            de_data['translation']['ui'][k] = val[5:]
        elif isinstance(val, str) and not val.startswith('[DE] '):
            pass # Keep it if it's already translated
        else:
             de_data['translation']['ui'][k] = v # Fallback to english raw instead of [DE]

with open('src/locales/de/translation.json', 'w') as f:
    json.dump(de_data, f, indent=2)

with open('src/locales/es/translation.json', 'r') as f:
    es_data = json.load(f)

for k, v in en_ui.items():
    if k in es_translations:
        es_data['translation']['ui'][k] = es_translations[k]
    else:
        # Strip [ES]
        val = es_data['translation']['ui'].get(k, '')
        if isinstance(val, str) and val.startswith('[ES] '):
            es_data['translation']['ui'][k] = val[5:]
        elif isinstance(val, str) and not val.startswith('[ES] '):
            pass
        else:
            es_data['translation']['ui'][k] = v

with open('src/locales/es/translation.json', 'w') as f:
    json.dump(es_data, f, indent=2)

print("Translations fixed successfully.")
